const E=(path,category,params=[],mode='provider',extra={})=>Object.freeze({path,category,params,mode,...extra});

export const catalog = Object.freeze([
  E('/ai/mathgpt','ai',['q'],'llm',{prompt:'Solve the math problem carefully and return a clear answer.'}),
  E('/ai/story','ai',['text'],'llm',{prompt:'Write a coherent story from the user prompt.'}),
  E('/aio','download',['url'],'media'),
  E('/aio3','download',['url'],'media'),
  E('/aivideo2','image',['q','type'],'provider'),
  E('/apk','search',['q'],'provider'),
  E('/bible','tools',['q'],'provider'),
  E('/bingimg','search',['q'],'provider'),
  E('/chatgpt','ai',['prompt'],'llm'),
  E('/colorize','image',['url','prompt'],'provider'),
  E('/convert','download',['url','format'],'media'),
  E('/copilot','ai',['q','prompt'],'llm'),
  E('/countries','tools',['q'],'countries'),
  E('/deepai','ai',['q','prompt','text'],'llm'),
  E('/download/ytmp3','download',['url'],'media',{format:'mp3'}),
  E('/elevenlab','ai',['list','q','voicename'],'provider'),
  E('/facebook2','download',['url'],'media'),
  E('/fakeigstory','image',['text','name','pp'],'provider'),
  E('/fbdown','download',['url'],'media'),
  E('/fdriod','search',['q'],'provider',{note:'Compatibility spelling preserved from the public API.'}),
  E('/firelogo','image',['text'],'provider'),
  E('/flux','image',['prompt'],'imageGenerate'),
  E('/font','tools',['text'],'font'),
  E('/fun/font','tools',['text'],'font'),
  E('/gemini','ai',['text','prompt'],'llm'),
  E('/gpt','ai',['prompt'],'llm'),
  E('/igdl','download',['url'],'media'),
  E('/image','search',['q'],'provider'),
  E('/imagine','image',['prompt'],'imageGenerate'),
  E('/img2pdf','tools',['url','images'],'provider'),
  E('/instagram','download',['url'],'media'),
  E('/insult','tools',[],'roast'),
  E('/lyrics','search',['query','q'],'lyrics'),
  E('/mediafire','download',['url'],'provider'),
  E('/money','tools',['amount','from','to'],'money'),
  E('/musicgen','ai',['prompt'],'provider'),
  E('/nsfw','image',['random','s'],'disabled',{reason:'Adult-content generation is intentionally disabled.'}),
  E('/ocr','tools',['url'],'provider'),
  E('/removebg','image',['url'],'provider'),
  E('/search/4kwallpaper','search',['q','type'],'provider'),
  E('/shazam','tools',['url'],'provider'),
  E('/spotify','download',['url'],'media'),
  E('/spotify1','download',['url','q'],'media'),
  E('/ssweb','tools',['url'],'provider'),
  E('/tempemail','email',['email'],'provider'),
  E('/tempurl','tools',['url'],'shorten'),
  E('/tiktok','download',['url'],'media'),
  E('/tiktok2','download',['url'],'media'),
  E('/tiktokdl','download',['url'],'media'),
  E('/tiktoksearch','search',['q'],'provider'),
  E('/toanime','image',['url','prompt'],'provider'),
  E('/tools/ocr','tools',['url'],'provider'),
  E('/upscaler','image',['url'],'provider'),
  E('/webcopier','tools',['url'],'webcopy'),
  E('/x','download',['url'],'media'),
  E('/ytdown','download',['url','format'],'media'),
  E('/ytmp3','download',['url'],'media',{format:'mp3'}),
  E('/ytmp4','download',['url'],'media',{format:'mp4'}),
  E('/ytsearch','search',['q'],'ytsearch'),

  // Publicly observed legacy/hidden compatibility routes.
  E('/aivideo','image',['q','type'],'provider',{legacy:true}),
  E('/analyze','ai',['url','question'],'provider',{legacy:true}),
  E('/carbon','image',['code'],'provider',{legacy:true}),
  E('/deepfake','image',['prompt','imageUrl'],'disabled',{legacy:true,reason:'Deepfake generation is intentionally disabled.'}),
  E('/pair','tools',['number'],'provider',{legacy:true}),
  E('/story','ai',['text'],'llm',{legacy:true,prompt:'Write a coherent story from the user prompt.'}),
  E('/tiktokstalk','search',['username'],'provider',{legacy:true}),
  E('/vocalremove','tools',['url'],'provider',{legacy:true}),
  E('/wasted','image',['url'],'provider',{legacy:true}),
  E('/ytaudio','download',['url'],'media',{legacy:true,format:'mp3'}),
  E('/zonerai','image',['prompt'],'imageGenerate',{legacy:true})
]);

export const byPath = new Map(catalog.map(x=>[x.path,x]));
export const dashboardCount = catalog.filter(x=>!x.legacy).length;
export const totalCount = catalog.length;
